=== admin-ch/CovidCertificate-Examples/schema/DGC.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://id.uvci.eu/DGC.schema.json",
  "title": "EU DGC",
  "description": "EU Digital Green Certificate",
  "required": [
    "ver",
    "nam",
    "dob"
  ],
  "type": "object",
  "properties": {
    "ver": {
      "title": "Schema version",
      "description": "Version of the schema, according to Semantic versioning (ISO, https://semver.org/ version 2.0.0 or newer)",
      "type": "string",
      "pattern": "^\\d+.\\d+.\\d+$",
      "examples": [
        "1.0.0"
      ]
    },
    "nam": {
      "description": "Surname(s), given name(s) - in that order",
      "$ref": "https://id.uvci.eu/DGC.Core.Types.schema.json#/$defs/person_name"
    },
    "dob": {
      "title": "Date of birth",
      "description": "Date of Birth of the person addressed in the DGC. ISO 8601 date format restricted to range 1900-2099",
      "type": "string",
      "format": "date",
      "pattern": "[19|20][0-9][0-9]-(0[1-9]|1[0-2])-([0-2][1-9]|3[0|1])",
      "examples": [
        "1979-04-14"
      ]
    },
    "v": {
      "description": "Vaccination Group",
      "type": "array",
      "items": {
        "$ref": "https://id.uvci.eu/DGC.Types.schema.json#/$defs/vaccination_entry"
      },
      "minItems": 1
    },
    "t": {
      "description": "Test Group",
      "type": "array",
      "items": {
        "$ref": "https://id.uvci.eu/DGC.Types.schema.json#/$defs/test_entry"
      },
      "minItems": 1
    },
    "r": {
      "description": "Recovery Group",
      "type": "array",
      "items": {
        "$ref": "https://id.uvci.eu/DGC.Types.schema.json#/$defs/recovery_entry"
      },
      "minItems": 1
    }
  }
}

=== admin-ch/CovidCertificate-Examples/examples/vac.json
{
    "ver": "1.0.0",
    "nam": {
        "fn": "d'Arsøns - van Halen",
        "gn": "François-Joan",
        "fnt": "DARSONS<VAN<HALEN",
        "gnt": "FRANCOIS<JOAN"
    },
    "dob": "2009-02-28",
    "v": [
        {
            "tg": "840539006",
            "vp": "1119349007",
            "mp": "EU/1/20/1528",
            "ma": "ORG-100030215",
            "dn": 1,
            "sd": 2,
            "dt": "2021-04-22",
            "co": "CH",
            "is": "Bundesamt für Gesundheit (BAG)",
            "ci": "01:CH:PlA8UWS60Z4RZVALl6GAZ:12"
        }
    ]
}

=== admin-ch/CovidCertificate-Examples/examples/test-rat.json
{
    "ver": "1.0.0",
    "nam": {
        "fn": "d'Arsøns - van Halen",
        "gn": "François-Joan",
        "fnt": "DARSONS<VAN<HALEN",
        "gnt": "FRANCOIS<JOAN"
    },
    "dob": "2009-02-28",
    "t": [
        {
            "tg": "840539006",
            "tt": "LP217198-3",
            "tr": "260415000",
            "ma": "1232",
            "sc": "2021-04-13T14:20:00+00:00",
            "dr": "2021-04-13T14:40:01+00:00",
            "tc": "Amavita Apotheke Bahnhof Bern",
            "co": "CH",
            "is": "Bundesamt für Gesundheit (BAG)",
            "ci": "01:CH:PlA8UWS60Z4RZVALl6GAZ:12"
        }
    ]
}

=== admin-ch/CovidCertificate-Examples/examples/contrived-translit.json
{
  "ver": "1.0.0",
  "nam": {
    "fn": "ابو بكر محمد بن زكريا الرازي",
    "fnt": "ABU<BAKR<MOHAMMED<IBN<ZAKARIA<AL<RAZI"
  },
  "dob": "2020-02-29",
  "v": [
    {
      "tg": "840539006",
      "vp": "1119349007",
      "mp": "EU/1/20/1528",
      "ma": "ORG-100030215",
      "dn": 2,
      "sd": 2,
      "dt": "2021-04-21",
      "co": "SA",
      "is": "Ministry of Public Health (MOH, وزارة الصحة)",
      "ci": "urn:uvci:01:NL:PlA8UWS60Z4RZXVALl6GAZ"
    }
  ]
}

=== admin-ch/CovidCertificate-Examples/examples/rec.json
{
    "ver": "1.0.0",
	"nam": {
        "fn": "Červenková Panklová",
        "fnt": "CERVENKOVA<PANKLOVA",
        "gn": "Jiřina Alena",
        "gnt": "JIRINA<ALENA"
    },
    "dob": "1987-03-22",
    "r": [
        {
            "tg": "840539006",
            "fr": "2021-04-22",
            "co": "CH",
            "is": "Bundesamt für Gesundheit (BAG)",
            "df": "2021-05-01",
            "du": "2021-10-21",
            "ci": "01:CH:PlA8UWS60Z4RZVALl6GAZ:12"
        }
    ]
}
